<?php $this->layout('email::layout/admin') ?>

<tr>
    <td class="wrapper">
        <table role="presentation" border="0" cellpadding="0" cellspacing="0">
            <tr>
                <td>
                    <p>Hi,</p>
                    <p>you recently requested to reset your password for your account. Click the button bellow to reset it.</p>

                    <table role="presentation" border="0" cellpadding="0" cellspacing="0" class="btn btn-primary">
                        <tbody>
                        <tr>
                            <td align="left">
                                <table role="presentation" border="0" cellpadding="0" cellspacing="0">
                                    <tbody>
                                    <tr>
                                        <td> <a href="<?= $recover_url ?>" target="_blank">Reset your Password</a> </td>
                                    </tr>
                                    </tbody>
                                </table>
                            </td>
                        </tr>
                        </tbody>
                    </table>

                    <p>If you did not request a password reset please ignore this email.
                        This password reset is only valid for the next <?= $minutes ?> minutes</p>
                </td>
            </tr>
        </table>
    </td>
</tr>