<!doctype html>
<?php
/** @var \KiwiSuite\Admin\Config\AdminConfig $adminConfig */
?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title><?= $adminConfig->name() ?></title>
    <base href="/<?= ltrim($adminConfig->uri()->getPath(), '/')?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no">
    <meta name="description" content="<?= $adminConfig->description() ?>">
    <meta name="author" content="<?= $adminConfig->author() ?>">
    <link rel="shortcut icon" href="<?= $this->asset('/admin/assets/img/favicon.png') ?>">
    <?php foreach ($assets['styles'] as $style): ?>
        <link href="<?= $this->asset($style) ?>" rel="stylesheet"/>
    <?php endforeach ?>
</head>
<body class="app header-fixed sidebar-fixed aside-menu-fixed">
<p></p>
<script>
    window.__theme = 'bs4';
    window.__kiwi = <?= json_encode([
        'project' => [
                'author' => $adminConfig->author(),
                'name' => $adminConfig->name(),
                'poweredBy' => $adminConfig->poweredBy(),
                'copyright' => $adminConfig->copyright(),
                'description' => $adminConfig->description(),
                'background' => $adminConfig->background(),
                'icon' => $adminConfig->icon(),
                'logo' => $adminConfig->logo(),
        ],
        'routes' => [
            'session' => $adminConfig->getUri()->getPath() . '/session',
            'config' => $adminConfig->getUri()->getPath() . '/api/config', //TODO use url helper
        ]
    ]) ?>;
</script>
<?php foreach ($assets['scripts'] as $script): ?>
    <script type="text/javascript" src="<?= $this->asset($script) ?>"></script>
<?php endforeach ?>
</body>
</html>
