<!doctype html>
<html lang="en">
<head>
    <?php
    /** @var \Ixocreate\Admin\Config\AdminConfig $adminConfig */
    $adminConfig = $this->admin()->getAdminConfig();
    $assets = $this->admin()->assetsPaths();
    ?>
    <meta charset="utf-8">
    <meta name="robots" content="none">
    <title><?= $adminConfig->name() ?></title>
    <base href="/<?= ltrim($adminConfig->uri()->getPath(), '/')?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no">
    <meta name="description" content="<?= $adminConfig->description() ?>">
    <meta name="author" content="<?= $adminConfig->author() ?>">
    <link rel="shortcut icon" href="<?= $adminConfig->icon() ?>">
    <?php foreach ($assets['styles'] as $style): ?>
        <link href="<?= $style ?>" rel="stylesheet"/>
    <?php endforeach ?>
    <?php if (!empty($adminConfig->googleMapApiKey())): ?>
        <script src="https://maps.googleapis.com/maps/api/js?key=<?= $adminConfig->googleMapApiKey() ?>&libraries=places"></script>
    <?php endif; ?>
</head>
<body class="app">
<script>
    window.__ixo = <?= json_encode([
        'googleApiKey' => $adminConfig->googleMapApiKey(),
        'project' => [
            'author' => $adminConfig->author(),
            'name' => $adminConfig->name(),
            'poweredBy' => $adminConfig->poweredBy(),
            'copyright' => $adminConfig->copyright(),
            'description' => $adminConfig->description(),
            'background' => $adminConfig->background(),
            'icon' => $adminConfig->icon(),
            'logo' => $adminConfig->logo(),
            'loginUrl' => $this->admin()->generateUri('admin.login'),
            'logoutUrl' => $this->admin()->generateUri('admin.logout'),
        ],
        'routes' => [
            'session' => rtrim($adminConfig->uri()->getPath(), '/') . '/session',
            'config' => rtrim($adminConfig->uri()->getPath(), '/') . '/api/config',
        ]
    ]) ?>;
</script>
<?php foreach ($assets['scripts'] as $script): ?>
    <script type="text/javascript" src="<?= $script ?>"></script>
<?php endforeach ?>
</body>
</html>
