<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Login :: swya</title>
    <base href="/admin">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no">

    <meta name="author" content="V Labs GmbH">
    <link rel="shortcut icon"
          href="http://swya-web.ixocreate72.test/asset/admin/favicon.ico?v=5d829966b120d73543d22aef65780b60f4e4a871">
    <link href="http://swya-web.ixocreate72.test/admin/static/styles.e1d5c36b7362b678e83e.css?v=dev-develop@96f2174f4f3d74defa01e7417518c766c41f1de3"
          rel="stylesheet">
</head>
<body>
<app-dashboard>
    <div class="app-body"><!---->
        <div class="app-body-background"
             style="background-image: url(&quot;http://swya-web.ixocreate72.test/asset/admin/swya-bg.jpg?v=50c897d9fd89db7ce623ed008887b50726038cf8&quot;);"></div>
        <main class="main d-flex align-items-center">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 mx-auto">
                        <div class="card-group">
                            <div class="card p-4">
                                <div class="card-body"><!---->
                                    <div class="text-center mb-2">
                                        <img style="width: 100px; height: 100px;"
                                                                       src="http://swya-web.ixocreate72.test/asset/admin/swya-logo.svg?v=50c897d9fd89db7ce623ed008887b50726038cf8">
                                    </div>
                                    <form novalidate="" class="ng-untouched ng-pristine ng-invalid">
                                        <div class="text-center"><p class="text-muted">Sign In to your account</p></div>
                                        <!---->
                                        <div class="input-group mb-3">
                                            <div class="input-group-prepend"><span class="input-group-text"><i
                                                            class="fa fa-user"></i></span></div>
                                            <input class="form-control ng-untouched ng-pristine ng-invalid"
                                                   formcontrolname="email" placeholder="Email" type="email"></div>
                                        <div class="input-group mb-4">
                                            <div class="input-group-prepend"><span class="input-group-text"><i
                                                            class="fa fa-lock"></i></span></div>
                                            <input class="form-control ng-untouched ng-pristine ng-invalid"
                                                   formcontrolname="password" placeholder="Password" type="password">
                                        </div>
                                        <div class="text-right">
                                            <button class="btn btn-primary px-4 btn-block" type="submit" disabled="">
                                                Login
                                            </button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div><!----></div>
                </div>
            </div>
        </main>
    </div>
</app-dashboard>
</body>
</html>
