<?php $this->layout('admin::layout/layout') ?>

<?php if ($errors): ?>
    <div class="alert alert-danger">
        <?php foreach ($errors as $error): ?>
            <div><?= $error ?></div>
        <?php endforeach; ?>
    </div>
<?php endif; ?>

<form method="post" action="">
    <div class="text-center"><p class="text-muted">Sign In to your account</p></div>

    <div class="input-group mb-3">
        <div class="input-group-prepend"><span class="input-group-text"><i
                        class="fa fa-user"></i></span></div>
        <input class="form-control" placeholder="Email" type="email" name="email" required>
    </div>
    <div class="input-group mb-4">
        <div class="input-group-prepend"><span class="input-group-text"><i
                        class="fa fa-lock"></i></span></div>
        <input class="form-control" placeholder="Password" type="password" name="password" required>
    </div>
    <input type="hidden" name="csrf" value="<?= $csrf ?>">
    <div class="text-right">
        <button class="btn btn-primary px-4 btn-block" type="submit">
            Login
        </button>
    </div>
</form>
