<?php $this->layout('admin::layout/auth') ?>

<form method="post" action="">
    <div class="text-center"><p class="text-muted">Request a new password</p></div>

    <div class="input-group mb-3">
        <div class="input-group-prepend"><span class="input-group-text"><i
                        class="fa fa-user"></i></span></div>
        <input class="form-control" placeholder="Email" type="email" name="email" required>
    </div>

    <input type="text" name="csrf" value="<?= $csrf ?>">
    <div class="text-right">
        <button class="btn btn-primary px-4 btn-block" type="submit">
            Request
        </button>
    </div>
</form>
