<?php
/**
 * @var Ixocreate\Admin\Config\AdminConfig $project
 * @var array $config
 * @var string $csrf
 * @var array $scripts
 * @var array $styles
 */
?>
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title><?= ($title ?? null) ? $title . ' - ' . $project->name() : $project->name() ?></title>
    <base href="/<?= ltrim($project->uri()->getPath(), '/') ?>">
    <meta name="author" content="<?= $project->author() ?>">
    <meta name="description" content="<?= $project->description() ?>">
    <meta name="robots" content="none">
    <meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no">
    <meta name="csrf-token" content="<?= $csrf ?>">
    <link rel="shortcut icon" href="<?= $project->icon() ?>">
    <?php foreach ($styles as $style): ?>
        <link href="<?= $this->asset($style) ?>" rel="stylesheet">
    <?php endforeach ?>
</head>
<body>
<div class="auth" <?= !empty($project->background()) ? 'style="background-image: url(' . $project->background() . ')"' : '' ?>>
    <div class="auth-content">
        <div class="auth-box">
            <?php if (!empty($project->loginMessage())): ?>
                <div class="auth-message"><?= $project->loginMessage() ?></div>
            <?php endif; ?>
            <?php if(!empty($project->loginLogo())): ?>
                <img class="auth-logo" alt="<?= $project->name() ?> Logo" src="<?= $project->loginLogo() ?>">
            <?php endif ?>
            <?= $this->section('content') ?>
        </div>
    </div>
</div>
<?php /*
// do not output scripts gathered via TemplateVariablesMiddleware here as it would expose the javascript application
// TODO: move/split the middleware or find another way of injecting them
<?php foreach ($scripts as $script): ?>
    <script type="text/javascript" src="<?= $this->asset($script) ?>"></script>
<?php endforeach ?>
*/?>
</body>
</html>
